// ........................................................
// mainTest2.js
// ........................................................
const Logica = require( "../Logica.js" )
var assert = require ('assert')
// ........................................................
// Hugo Martin Escrihuela
// ........................................................
// ........................................................
// main ()
// ........................................................
describe( "Tarea 5: Funciones basicas de Dispositivo", function() {
    // ....................................................
    // ....................................................
    var laLogica = null
    // ....................................................
    // ....................................................
    it( "conectar a la base de datos", function( hecho ) {
        laLogica = new Logica(
            "../bd/datos.bd",
            function( err ) {
                if ( err ) {
                    throw new Error ("No he podido conectar con datos.db")
                }
                hecho()
            })
    }) // it
    // ....................................................
    // ....................................................
    // ....................................................
    // ....................................................
    it("Inserto un dispositivo", async function () {
        await laLogica.insertarDispositivo({ dispositivo_id: 'dispositivoprueba', dni_empleado: '44444443Insert' })
    }) // it

    // ....................................................
    // ....................................................
    it("Actualizo un dispositivo", async function () {
        await laLogica.actualizarDispositivo({ dispositivo_id: 'dispositivoprueba', dni_empleado: '44444443Insert' })
    }) // it

    // ....................................................
    // ....................................................
    it("Busco todos los dispositivos", async function () {
        await laLogica.getTodosLosDispositivos()
    }) // it

    // ....................................................
    // ....................................................
    it("Busco dispositivos por dni de empleado", async function () {
        await laLogica.getDispositivoPorPersona('44444443Insert')
    }) // it

    // ....................................................
    // ....................................................
    it("Busco dispositivos por zona/codigo postal", async function () {
        await laLogica.getDispositivosPorZona('12345')
    }) // it

    // ....................................................
    // ....................................................
    it("Busco dispositivos por admin", async function () {
        await laLogica.getDispositivosPorAdmin('44444443Insert')
    }) // it


    // ....................................................
    // ....................................................
    it("Borrar un dispositivo por su id",
        async function () {
            await laLogica.borrarDispositivoPorId('dispositivoprueba')
        }) // it

    // ....................................................
    // ....................................................
    it( "cerrar conexión a la base de datos",
        async function() {
            try {
                await laLogica.cerrar()
            } catch( err ) {
            // assert.equal( 0, 1, "cerrar conexión a BD fallada: " + err)
                throw new Error( "cerrar conexión a BD fallada: " + err)
            }
    }) // it
})