// ........................................................
// mainTest2.js
// ........................................................
const Logica = require( "../Logica.js" )
var assert = require ('assert')
// ........................................................
// Hugo Martin Escrihuela
// ........................................................
// ........................................................
// main ()
// ........................................................
describe( "Tarea 2: Funciones basicas de Admin", function() {
    // ....................................................
    // ....................................................
    var laLogica = null
    // ....................................................
    // ....................................................
    it("conectar a la base de datos", function (hecho) {
        laLogica = new Logica(
            "../bd/datos.bd",
            function (err) {
                if (err) {
                    throw new Error("No he podido conectar con datos.db")
                }
                hecho()
            })
    }) // it
    // ....................................................
    // ....................................................
    it("Primero vacio la bd", async function () {
        await laLogica.borrarTodasLasTablas()
    }) // it
    // ....................................................
    // ....................................................
    it("Primero borro los admins que pueda haber en la bbdd", async function () {
        await laLogica.borrarAdmins()
            var res = await laLogica.getTodosLosAdmins()
            assert.equal( res.length, 0, "¿hay un resulado?" )
    }) // it
    // ....................................................
    // ....................................................
    it("Inserto una persona para que funcione el admin", async function () {
        var persona = { dni: '12345678A', nombre: 'Juan', apellidos: 'Mata', correo: 'juanmata@gmail.com', telefono: '666666666' }
        await laLogica.insertarPersona(persona)
    }) // it
    // ....................................................
    // ....................................................
    it("Inserto un admin", async function () {
        var admin = { dni_admin: '12345678A', contrasenya: '123456789' }
        await laLogica.insertarAdmin(admin)
    }) // it
    // ....................................................
    // ....................................................
    it("Actualizo un admin", async function () {
        var admin = { dni_admin: '12345678A', contrasenya: '987654321' }
        await laLogica.actualizarAdmin(admin)
    }) // it
    // ....................................................
    // ....................................................
    it("Busco el admin anteriormente introducido",
        async function () {
            var res = await laLogica.getAdminPorDNI('12345678A')
                assert.equal( res.length, 1, "¿no hay un resulado?" )
                assert.equal( res[0].contrasenya, '987654321', "¿no es 987654321?" )
    }) // it
    // ....................................................
    // ....................................................
    it("Busco todos los admins",
        async function () {
            var res = await laLogica.getTodosLosAdmins()
                assert.equal( res.length, 1, "¿no hay un resulado?" )
                assert.equal( res[0].contrasenya, '987654321', "¿no es 987654321?" )
        }) // it
    // ....................................................
    // ....................................................
    it("Busco admin por correo",
        async function () {
            var res = await laLogica.getAdminPorCorreo('juanmata@gmail.com')
                assert.equal( res.length, 1, "¿no hay un resulado?" )
                assert.equal( res[0].contrasenya, '987654321', "¿no es 987654321?" )
    }) // it
    // ....................................................
    // ....................................................
    it("Borro admin por dni",
        async function () {
            await laLogica.borrarAdminPorDNI('12345678A')
    }) // it
    // ....................................................
    // ....................................................
    it("Compruebo que el admin se ha borrado",
        async function () {
            var res = await laLogica.getAdminPorDNI('12345678A')
                assert.equal( res.length, 0, "¿hay un resulado?" )
    }) // it
    // ....................................................
    // ....................................................
    it( "cerrar conexión a la base de datos",
        async function() {
            try {
                await laLogica.cerrar()
            } catch( err ) {
            // assert.equal( 0, 1, "cerrar conexión a BD fallada: " + err)
                throw new Error( "cerrar conexión a BD fallada: " + err)
            }
    }) // it
})