// ........................................................
// mainTest2.js
// ........................................................
const Logica = require( "../Logica.js" )
var assert = require ('assert')
// ........................................................
// Hugo Martin Escrihuela
// ........................................................
// ........................................................
// main ()
// ........................................................
describe( "Tarea 3: Funciones basicas de Zona_Admin", function() {
    // ....................................................
    // ....................................................
    var laLogica = null
    // ....................................................
    // ....................................................
    it("conectar a la base de datos", function (hecho) {
        laLogica = new Logica(
            "../bd/datos.bd",
            function (err) {
                if (err) {
                    throw new Error("No he podido conectar con datos.db")
                }
                hecho()
            })
    }) // it
    // ....................................................
    // ....................................................
    it("Primero vacio la bd", async function () {
        await laLogica.borrarTodasLasTablas()
    }) // it
    // ....................................................
    // ....................................................
    it("Primero borro zonas que pueda haber en la bbdd", async function () {
        await laLogica.borrarTodasLasZonas()
            var res = await laLogica.getTodasLasZonas()
            assert.equal( res.length, 0, "¿hay un resulado?" )
    }) // it
    // ....................................................
    // ....................................................
    it("Inserto una persona para que funcione la zona", async function () {
        var persona = { dni: '12345678A', nombre: 'Juan', apellidos: 'Mata', correo: 'juanmata@gmail.com', telefono: '666666666' }
        await laLogica.insertarPersona(persona)
    }) // it
    // ....................................................
    // ....................................................
    it("Inserto un admin para que funcione la zona", async function () {
        var admin = { dni_admin: '12345678A', contrasenya: '123456789' }
        await laLogica.insertarAdmin(admin)
    }) // it
    // ....................................................
    // ....................................................
    it("Inserto la zona", async function () {
        var zona = { dni_admin: '12345678A', zona: '03601' }
        await laLogica.insertarZonaAdmin(zona)
    }) // it
    // ....................................................
    // ....................................................
    it("Actualizo la zona", async function () {
        var zona = { dni_admin: '12345678A', zona: '03602' }
        await laLogica.actualizarZonaAdmin(zona)
    }) // it
    // ....................................................
    // ....................................................
    it("Busco la zona anteriormente introducida",
        async function () {
            var res = await laLogica.getZonaPorDNI('12345678A')
                assert.equal( res.length, 1, "¿no hay un resulado?" )
                assert.equal( res[0].zona, '03602', "¿no es 03602?" )
    }) // it
    // ....................................................
    // ....................................................
    it("Busco todas las zonas",
        async function () {
            var res = await laLogica.getTodasLasZonas()
                assert.equal( res.length, 1, "¿no hay un resulado?" )
                assert.equal( res[0].zona, '03602', "¿no es 03602?" )
        }) // it
    // ....................................................
    // ....................................................
    it("Borro zona por dni",
        async function () {
            await laLogica.borrarZonaPorDNI('12345678A')
    }) // it
    // ....................................................
    // ....................................................
    it("Compruebo que la zona se ha borrado",
        async function () {
            var res = await laLogica.getZonaPorDNI('12345678A')
                assert.equal( res.length, 0, "¿hay un resulado?" )
    }) // it
    // ....................................................
    // ....................................................
    it( "cerrar conexión a la base de datos",
        async function() {
            try {
                await laLogica.cerrar()
            } catch( err ) {
            // assert.equal( 0, 1, "cerrar conexión a BD fallada: " + err)
                throw new Error( "cerrar conexión a BD fallada: " + err)
            }
    }) // it
})