// ........................................................
// mainTest2.js
// ........................................................
const Logica = require( "../Logica.js" )
var assert = require ('assert')
// ........................................................
// Hugo Martin Escrihuela
// ........................................................
// ........................................................
// main ()
// ........................................................
describe( "Tarea 4: Funciones basicas de TipoValor", function() {
    // ....................................................
    // ....................................................
    var laLogica = null
    // ....................................................
    // ....................................................
    it( "conectar a la base de datos", function( hecho ) {
        laLogica = new Logica(
            "../bd/datos.bd",
            function( err ) {
                if ( err ) {
                    throw new Error ("No he podido conectar con datos.db")
                }
                hecho()
            })
    }) // it
    // ....................................................
    // ....................................................
    // ....................................................
    // ....................................................
    it("Inserto un TipoValor", async function () {
        await laLogica.insertarTipoValor({ tipo_valor_id: 4, tipo_valor: "Prueba"})
    }) // it

    // ....................................................
    // ....................................................
    it( "Busco todos los TipoValor",
        async function() {
            await laLogica.getTodosLosTipoValor()
    }) // it

    // ....................................................
    // ....................................................
    it("Borrar el TipoValor",
        async function () {
            await laLogica.borrarTipoValor(4)
        }) // it

    // ....................................................
    // ....................................................
    it( "cerrar conexión a la base de datos",
        async function() {
            try {
                await laLogica.cerrar()
            } catch( err ) {
            // assert.equal( 0, 1, "cerrar conexión a BD fallada: " + err)
                throw new Error( "cerrar conexión a BD fallada: " + err)
            }
    }) // it
})